### ISSUE TITLE
Need a plugin name

### ISSUE THREAD

**Issue by justintadlock** [justintadlock/toot#1]
Right now, I'm just calling this "Hybrid Testimonials".  "Testimonials" is already taken in the .ORG directory.

Any good synonyms or funky names?

**Comment by m-e-h** [comment]
- Compliments
- Tributes

or I kinda like
- Beep Beep 
as in:

> Don't mean to toot my on horn but... beep, beep :smiley:

**Comment by justintadlock** [comment]
I kind of like "Toot". :)

**Comment by samikeijonen** [comment]
For brand I'd keep Hybrid Testimonials or similar. But "Toot" is way more fun:)

**Comment by justintadlock** [comment]
Decided to go with Toot.  Everything, including this repository, is now renamed.
